public enum ObserverKey
{
    ON_CLICK_HOLE,
    ON_CLICK_PEOPLE,
    ON_PEOPLE_MOVE_TO_HOLE_FINISH,
    ON_HOLE_OUT_FULL,
    ON_REMOVE_HOLE_OUT,
    ON_CHANGE_HEART,
    ON_CHANGE_COIN,
    ON_CHANGE_EXTRA_SLOT,
    ON_CHANGE_RAINBOW_HOLE,
    ON_CHANGE_UFO,
    ON_END_GAME,
    ON_REMOVE_ENTITY_FROM_GRID,
    ON_LOAD_REMOTE_CONFIG_DONE,
    ON_REMOVE_PEOPLE,
    ON_PEOPLE_MOVE_TO_HOLE_OUT_FINISH
}